version: '3'
services:
  dev_linux:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    tty: True
    volumes:
      - ./cpp:/tmp/project
      - ./template:/tmp/src/template
  #dev_win:
  #  build:
  #    context: .
  #    dockerfile: ./Docker/windows/Dockerfile
  #  volumes:
  #    - ./cpp:C:/TEMP
  #  tty: True