version: '3'
services:
  #dev_linux:
  #  build:
  #    context: .
  #    dockerfile: ./Docker/alpine/Dockerfile
  #  tty: True
  #  volumes:
  #    - ./cpp:/tmp/project
  dev_win:
    build:
      context: .
      dockerfile: ./Docker/windows/Dockerfile
    volumes:
      - ./cpp:C:/TEMP
    tty: True